version: '3.8'

services:
  web:
    build: .
    container_name: basic-web-app-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALLOWED_ORIGINS=http://${VPS_IP},https://${VPS_IP},http://${DOMAIN:-localhost:3000}
      - SESSION_SECRET=${SESSION_SECRET}
      - LOG_LEVEL=info
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - APP_NAME=Basic Web App
      - APP_VERSION=1.0.0
      - TRUST_PROXY=true
      - COMPRESSION_LEVEL=6
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: basic-web-app-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.template.conf:/etc/nginx/templates/default.conf.template:ro
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - VPS_IP=${VPS_IP}
      - DOMAIN=${DOMAIN:-$VPS_IP}
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs: 